FROM ghcr.io/strongestnumber9/ipa_01/client/9:latest
RUN dnf install -y java-11-openjdk-headless
COPY config/config-patch.json /config.json
COPY config/cluster.properties /cluster.properties
COPY config/producer.properties /producer.properties
COPY config/kaf_05/credentials.json /credentials.json
COPY rpm/kaf_06.rpm /kaf_06.rpm
RUN rpm -ivh --nodeps /kaf_06.rpm
COPY files/entrypoint.manager.sh /ipa_01.conf.d/post/entrypoint.sh
